version: '3.7'
services: 
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - "./apps/${APP_NAME}/public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
     - php

  php: 
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - "./apps/${APP_NAME}/:/usr/src/app"
    env_file: 
      - .env
    user: 1000:1000